name: Deploy to Vercel (Static Site)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}        
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}          
      VERCEL_PROJECT_NAME: college-course-selector      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List repo (debug)
        run: |
          ls -la
          echo "Node (pre):" && node -v || true
          echo "NPM  (pre):" && npm -v  || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Vercel pull
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            vercel pull --yes --environment=preview \
              --project "$VERCEL_PROJECT_NAME" \
              --scope "$VERCEL_SCOPE" \
              --token "$VERCEL_TOKEN"
          else
            vercel pull --yes --environment=production \
              --project "$VERCEL_PROJECT_NAME" \
              --scope "$VERCEL_SCOPE" \
              --token "$VERCEL_TOKEN"
          fi

      - name: Build
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            vercel build \
              --project "$VERCEL_PROJECT_NAME" \
              --scope "$VERCEL_SCOPE" \
              --token "$VERCEL_TOKEN"
          else
            vercel build --prod \
              --project "$VERCEL_PROJECT_NAME" \
              --scope "$VERCEL_SCOPE" \
              --token "$VERCEL_TOKEN"
          fi

      - name: Deploy
        id: deploy
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            URL=$(vercel deploy --prebuilt \
              --project "$VERCEL_PROJECT_NAME" \
              --scope "$VERCEL_SCOPE" \
              --token "$VERCEL_TOKEN")
            echo "preview_url=$URL" >> $GITHUB_OUTPUT
          else
            URL=$(vercel deploy --prebuilt --prod \
              --project "$VERCEL_PROJECT_NAME" \
              --scope "$VERCEL_SCOPE" \
              --token "$VERCEL_TOKEN")
            echo "prod_url=$URL" >> $GITHUB_OUTPUT
          fi

      - name: Summary
        if: always()
        run: |
          echo "### Vercel deployment" >> $GITHUB_STEP_SUMMARY
          echo "- Preview: ${{ steps.deploy.outputs.preview_url }}" >> $GITHUB_STEP_SUMMARY
          echo "- Production: ${{ steps.deploy.outputs.prod_url }}" >> $GITHUB_STEP_SUMMARY
